[2024-12-25T01:41:17.503+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-25T01:41:17.539+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_train_version_mlflow manual__2024-12-25T01:02:02.167083+00:00 [queued]>
[2024-12-25T01:41:17.560+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_train_version_mlflow manual__2024-12-25T01:02:02.167083+00:00 [queued]>
[2024-12-25T01:41:17.561+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-12-25T01:41:17.587+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): step_train_version_mlflow> on 2024-12-25 01:02:02.167083+00:00
[2024-12-25T01:41:17.619+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_Pipeline_ETL_and_ML_Training', 'step_train_version_mlflow', 'manual__2024-12-25T01:02:02.167083+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_train_pipeline.py', '--cfg-path', '/tmp/tmpe3m6n_61']
[2024-12-25T01:41:17.624+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask step_train_version_mlflow
[2024-12-25T01:41:17.626+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=372) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-25T01:41:17.628+0000] {standard_task_runner.py:72} INFO - Started process 381 to run task
[2024-12-25T01:41:17.713+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_train_version_mlflow manual__2024-12-25T01:02:02.167083+00:00 [running]> on host 5408e77d1c99
[2024-12-25T01:41:17.883+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='NY_Pipeline_ETL_and_ML_Training' AIRFLOW_CTX_TASK_ID='step_train_version_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2024-12-25T01:02:02.167083+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-25T01:02:02.167083+00:00'
[2024-12-25T01:41:17.884+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-25T01:41:19.361+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/airflow_server/dags/etl_train_pipeline_modules/pipeline_train.py", line 13, in train_and_version_mlflow
    mlflow.set_experiment("regression_models_ny_housing")
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 182, in set_experiment
    raise MlflowException(
mlflow.exceptions.MlflowException: Cannot set a deleted experiment 'regression_models_ny_housing' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.
[2024-12-25T01:41:19.412+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=NY_Pipeline_ETL_and_ML_Training, task_id=step_train_version_mlflow, run_id=manual__2024-12-25T01:02:02.167083+00:00, execution_date=20241225T010202, start_date=20241225T014117, end_date=20241225T014119
[2024-12-25T01:41:19.455+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-25T01:41:19.457+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task step_train_version_mlflow (Cannot set a deleted experiment 'regression_models_ny_housing' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.; 381)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/airflow_server/dags/etl_train_pipeline_modules/pipeline_train.py", line 13, in train_and_version_mlflow
    mlflow.set_experiment("regression_models_ny_housing")
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 182, in set_experiment
    raise MlflowException(
mlflow.exceptions.MlflowException: Cannot set a deleted experiment 'regression_models_ny_housing' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.
[2024-12-25T01:41:19.535+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-25T01:41:19.566+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-25T01:41:19.571+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
