[2024-12-28T15:05:38.743+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T15:05:38.780+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_train_version_mlflow manual__2024-12-28T14:48:45.709776+00:00 [queued]>
[2024-12-28T15:05:38.806+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_train_version_mlflow manual__2024-12-28T14:48:45.709776+00:00 [queued]>
[2024-12-28T15:05:38.807+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-28T15:05:38.834+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): step_train_version_mlflow> on 2024-12-28 14:48:45.709776+00:00
[2024-12-28T15:05:38.866+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_Pipeline_ETL_and_ML_Training', 'step_train_version_mlflow', 'manual__2024-12-28T14:48:45.709776+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_train_pipeline.py', '--cfg-path', '/tmp/tmp9yuxpewj']
[2024-12-28T15:05:38.871+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask step_train_version_mlflow
[2024-12-28T15:05:38.871+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=529) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-28T15:05:38.873+0000] {standard_task_runner.py:72} INFO - Started process 549 to run task
[2024-12-28T15:05:38.962+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_train_version_mlflow manual__2024-12-28T14:48:45.709776+00:00 [running]> on host c37d744c8c7d
[2024-12-28T15:05:39.122+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='NY_Pipeline_ETL_and_ML_Training' AIRFLOW_CTX_TASK_ID='step_train_version_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T14:48:45.709776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T14:48:45.709776+00:00'
[2024-12-28T15:05:39.130+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T15:05:41.893+0000] {logging_mixin.py:190} WARNING - 2024/12/28 15:05:41 INFO mlflow.tracking.fluent: Experiment with name 'regression_models_ny_housing' does not exist. Creating a new experiment.
[2024-12-28T15:05:46.294+0000] {logging_mixin.py:190} INFO - Database connection closed.
[2024-12-28T15:05:46.295+0000] {logging_mixin.py:190} INFO - Database connection closed.
[2024-12-28T15:05:46.660+0000] {logging_mixin.py:190} WARNING - 2024/12/28 15:05:46 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-12-28T15:05:46.827+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2024-12-28T15:26:48.621+0000] {job.py:229} INFO - Heartbeat recovered after 467.69 seconds
[2024-12-28T15:27:04.004+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-28T15:27:04.017+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-28T15:27:04.050+0000] {process_utils.py:132} INFO - Sending 15 to group 549. PIDs of all processes in the group: [549]
[2024-12-28T15:27:04.052+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 549
[2024-12-28T15:27:04.182+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-28T15:27:04.286+0000] {logging_mixin.py:190} INFO - üèÉ View run judicious-snake-955 at: http://mlflow:5000/#/experiments/1/runs/080a7bc5b2c948a8adb3979e23ab10cb
[2024-12-28T15:27:04.288+0000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2024-12-28T15:27:04.406+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T15:27:04.454+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=549, status='terminated', exitcode=0, started='15:05:38') (549) terminated with exit code 0
