[2024-12-23T19:24:41.283+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T19:24:41.315+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T19:24:41.337+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T19:24:41.339+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-12-23T19:24:41.371+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): step_create_original_table> on 2024-12-22 00:00:00+00:00
[2024-12-23T19:24:41.386+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_Pipeline_ETL_and_ML_Training', 'step_create_original_table', 'scheduled__2024-12-22T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_train_pipeline.py', '--cfg-path', '/tmp/tmpz5py5zuw']
[2024-12-23T19:24:41.393+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask step_create_original_table
[2024-12-23T19:24:41.401+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-23T19:24:41.405+0000] {standard_task_runner.py:72} INFO - Started process 241 to run task
[2024-12-23T19:24:41.510+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [running]> on host 6a8ed8f14bf7
[2024-12-23T19:24:41.685+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='NY_Pipeline_ETL_and_ML_Training' AIRFLOW_CTX_TASK_ID='step_create_original_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T00:00:00+00:00'
[2024-12-23T19:24:41.690+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T19:24:41.788+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/airflow_server/dags/etl_train_pipeline_modules/dsa_carrega_dados.py", line 16, in load_csv_to_postgresql
    username=os.environ["DB_USER"],
             ~~~~~~~~~~^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'DB_USER'
[2024-12-23T19:24:41.818+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=NY_Pipeline_ETL_and_ML_Training, task_id=step_create_original_table, run_id=scheduled__2024-12-22T00:00:00+00:00, execution_date=20241222T000000, start_date=20241223T192441, end_date=20241223T192441
[2024-12-23T19:24:41.890+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T19:24:41.892+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task step_create_original_table ('DB_USER'; 241)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/airflow_server/dags/etl_train_pipeline_modules/dsa_carrega_dados.py", line 16, in load_csv_to_postgresql
    username=os.environ["DB_USER"],
             ~~~~~~~~~~^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'DB_USER'
[2024-12-23T19:24:41.910+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-23T19:24:41.937+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T19:24:41.940+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-23T20:06:21.343+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T20:06:21.400+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T20:06:21.444+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T20:06:21.446+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-12-23T20:06:21.502+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): step_create_original_table> on 2024-12-22 00:00:00+00:00
[2024-12-23T20:06:21.586+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_Pipeline_ETL_and_ML_Training', 'step_create_original_table', 'scheduled__2024-12-22T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_train_pipeline.py', '--cfg-path', '/tmp/tmpspz5rqzz']
[2024-12-23T20:06:21.607+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-23T20:06:21.611+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask step_create_original_table
[2024-12-23T20:06:21.612+0000] {standard_task_runner.py:72} INFO - Started process 242 to run task
[2024-12-23T20:06:21.918+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [running]> on host 9b703ff31b63
[2024-12-23T20:06:22.285+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='NY_Pipeline_ETL_and_ML_Training' AIRFLOW_CTX_TASK_ID='step_create_original_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T00:00:00+00:00'
[2024-12-23T20:06:22.302+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T20:06:22.465+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/airflow_server/dags/etl_train_pipeline_modules/dsa_carrega_dados.py", line 16, in load_csv_to_postgresql
    username=os.getenv["DB_USER"],
             ~~~~~~~~~^^^^^^^^^^^
TypeError: 'function' object is not subscriptable
[2024-12-23T20:06:22.553+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=NY_Pipeline_ETL_and_ML_Training, task_id=step_create_original_table, run_id=scheduled__2024-12-22T00:00:00+00:00, execution_date=20241222T000000, start_date=20241223T200621, end_date=20241223T200622
[2024-12-23T20:06:22.644+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T20:06:22.649+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task step_create_original_table ('function' object is not subscriptable; 242)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/airflow_server/dags/etl_train_pipeline_modules/dsa_carrega_dados.py", line 16, in load_csv_to_postgresql
    username=os.getenv["DB_USER"],
             ~~~~~~~~~^^^^^^^^^^^
TypeError: 'function' object is not subscriptable
[2024-12-23T20:06:22.762+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-23T20:06:22.827+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T20:06:22.831+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-23T22:15:23.961+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T22:15:24.033+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T22:15:24.055+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T22:15:24.056+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-12-23T22:15:24.093+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): step_create_original_table> on 2024-12-22 00:00:00+00:00
[2024-12-23T22:15:24.174+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=201) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-23T22:15:24.205+0000] {standard_task_runner.py:72} INFO - Started process 203 to run task
[2024-12-23T22:15:24.139+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_Pipeline_ETL_and_ML_Training', 'step_create_original_table', 'scheduled__2024-12-22T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_train_pipeline.py', '--cfg-path', '/tmp/tmp_6xbj5_k']
[2024-12-23T22:15:24.217+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask step_create_original_table
[2024-12-23T22:15:24.535+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [running]> on host 4774a7bd2972
[2024-12-23T22:15:24.987+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='NY_Pipeline_ETL_and_ML_Training' AIRFLOW_CTX_TASK_ID='step_create_original_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T00:00:00+00:00'
[2024-12-23T22:15:25.024+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T22:15:25.181+0000] {logging_mixin.py:190} INFO - An error occurred: [Errno 2] No such file or directory: '***_server\\dags\\data\\NY-House-Dataset.csv'
[2024-12-23T22:15:25.183+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-23T22:15:25.209+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T22:15:25.211+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=NY_Pipeline_ETL_and_ML_Training, task_id=step_create_original_table, run_id=scheduled__2024-12-22T00:00:00+00:00, execution_date=20241222T000000, start_date=20241223T221524, end_date=20241223T221525
[2024-12-23T22:15:25.282+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-23T22:15:25.313+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T22:15:25.359+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-23T23:36:37.515+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T23:36:37.564+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T23:36:37.588+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T23:36:37.589+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-12-23T23:36:37.622+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): step_create_original_table> on 2024-12-22 00:00:00+00:00
[2024-12-23T23:36:37.641+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_Pipeline_ETL_and_ML_Training', 'step_create_original_table', 'scheduled__2024-12-22T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl_train_pipeline.py', '--cfg-path', '/tmp/tmpf4g_e5vi']
[2024-12-23T23:36:37.647+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask step_create_original_table
[2024-12-23T23:36:37.658+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=309) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-23T23:36:37.659+0000] {standard_task_runner.py:72} INFO - Started process 312 to run task
[2024-12-23T23:36:37.781+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_Pipeline_ETL_and_ML_Training.step_create_original_table scheduled__2024-12-22T00:00:00+00:00 [running]> on host 8a0d5a4738c0
[2024-12-23T23:36:38.054+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='NY_Pipeline_ETL_and_ML_Training' AIRFLOW_CTX_TASK_ID='step_create_original_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T00:00:00+00:00'
[2024-12-23T23:36:38.060+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T23:36:38.276+0000] {logging_mixin.py:190} WARNING - /opt/***/***_server/dags/etl_train_pipeline_modules/dsa_carrega_dados.py:56 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-12-23T23:36:38.288+0000] {logging_mixin.py:190} INFO - An error occurred: BROKERTITLE (VARCHAR(255)) not a string
[2024-12-23T23:36:38.291+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-23T23:36:38.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T23:36:38.390+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=NY_Pipeline_ETL_and_ML_Training, task_id=step_create_original_table, run_id=scheduled__2024-12-22T00:00:00+00:00, execution_date=20241222T000000, start_date=20241223T233637, end_date=20241223T233638
[2024-12-23T23:36:38.467+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-23T23:36:38.504+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T23:36:38.509+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
